/**
 * Object id -> [internal name, display name, cost, extra], per rules type list.
 *
 * Generated on 2026-08-19 from a retail RA2 install, by a script that no longer
 * exists — the install dependency is gone and `scripts/fixture-replay-types.mjs`
 * rebuilds this shape from a harvest instead. Do not edit by hand.
 *
 * This is the **bootstrap** table, not the authority. `src/options.js` installs
 * the one harvested from the player's own client over it as soon as there is
 * one, and that one is better: the client layers `rulescd.ini` over `rules.ini`,
 * so its values are the ones in play, and `ra2cd.mix` already appends to
 * `[BuildingTypes]` — which this table, built from retail text, cannot know
 * about. What this file is for is the profile that has not harvested yet, which
 * would otherwise read `building #12` for every row of its first report.
 *
 * A replay states what was built as an ordinal into these lists and nothing
 * else, so this table is what makes a build order readable; src/replay.js falls
 * back to "vehicle #9" without it. Why it is committed although it is generated:
 * the source is a local RA2 install, which nobody running the extension has.
 *
 * `extra` is present only where there is something to say: `factory` (which
 * queue's production speed this building counts towards), `docks` (helipad
 * capacity, which is the whole of the aircraft queue's size), `limit`
 * (`BuildLimit`) and `cat` (`"combat"` for a building the game puts on the
 * Defence tab rather than Structures — `BuildCat=Combat`, which is what
 * `getQueueTypeForObject` reads), `tech` (`TechLevel`), `only` (the
 * `RequiredHouses` list, which is what makes something a country unit) and
 * `side` — which side can build it at all, resolved through the prerequisite
 * chain to one of the two construction yards, because `Owner=` says both for
 * almost everything. `__cdcReplayRules` carries the `[General]` settings every
 * queue's capacity is derived from.
 */
(() => {
  "use strict";
  window.__cdcReplayTypes = {
    building: [
      ["GAPOWR","Power Plant",800,{"tech":1,"side":"Allied"}],
      ["GAREFN","Allied Ore Refinery",2000,{"tech":1,"side":"Allied"}],
      ["GACNST","Allied Construction Yard",3000,{"factory":"BuildingType","side":"Allied"}],
      ["GAPILE","Allied Barracks",500,{"factory":"InfantryType","tech":2,"side":"Allied"}],
      ["GASAND","Sandbags",25,{"cat":"combat"}],
      ["GADEPT","Allied Service Depot",800,{"tech":6,"side":"Allied"}],
      ["GATECH","Allied Battle Lab",2000,{"tech":8,"side":"Allied"}],
      ["GAWEAP","Allied War Factory",2000,{"factory":"UnitType","tech":2,"side":"Allied"}],
      ["CALAB","RA2 Einstein's Lab",0],
      ["NAPOWR","Tesla Reactor",600,{"tech":1,"side":"Soviet"}],
      ["NATECH","Soviet Battle Lab",2000,{"tech":7,"side":"Soviet"}],
      ["NAHAND","Soviet Barracks",500,{"factory":"InfantryType","tech":2,"side":"Soviet"}],
      ["GAWALL","Allied Wall",100,{"cat":"combat","tech":1,"side":"Allied"}],
      ["NARADR","Radar Tower",1000,{"tech":3,"side":"Soviet"}],
      ["NAWEAP","Soviet War Factory",2000,{"factory":"UnitType","tech":2,"side":"Soviet"}],
      ["NAREFN","Soviet Ore Refinery",2000,{"tech":1,"side":"Soviet"}],
      ["NAWALL","Soviet Wall",100,{"cat":"combat","tech":1,"side":"Soviet"}],
      ["CAHSE07","RA2 American House 07",0],
      ["NAPSIS","Psychic Sensor",1000,{"cat":"combat","tech":10,"side":"Soviet"}],
      ["NAWAST","",0],
      ["NALASR","Sentry Gun",500,{"cat":"combat","tech":1,"side":"Soviet"}],
      ["NASAM","Patriot Missile",1000,{"cat":"combat","tech":4,"side":"Allied"}],
      ["GARADR","",0],
      ["GAYARD","Allied Shipyard",1000,{"factory":"UnitType","tech":4,"side":"Allied"}],
      ["NAIRON","Iron Curtain Device",2500,{"limit":1,"cat":"combat","tech":10,"side":"Soviet"}],
      ["NACNST","Soviet Construction Yard",3000,{"factory":"BuildingType","side":"Soviet"}],
      ["NADEPT","Soviet Service Depot",800,{"tech":6,"side":"Soviet"}],
      ["GACSPH","Chrono Sphere",2500,{"limit":1,"cat":"combat","tech":10,"side":"Allied"}],
      ["GADUMY","Dummy ChronoSphere",2800,{"side":"Allied"}],
      ["GAWEAT","Weather Controller",5000,{"limit":1,"cat":"combat","tech":10,"side":"Allied"}],
      ["CABHUT","Bridge repair hut",0],
      ["GALITE","Light Post",200],
      ["REDLAMP","Red Light Post",0],
      ["GRENLAMP","Green Light Post",0],
      ["BLUELAMP","Blue Light Post",0],
      ["YELWLAMP","Yellow Light Post",0],
      ["PURPLAMP","Purple Light Post",0],
      ["INORANLAMP","Orange Light Post",0],
      ["INGRNLMP","Invisible Green Light Post",0],
      ["INREDLMP","Invisible Red Light Post",0],
      ["INBLULMP","Invisible Blue Light Post",0],
      ["CITY01","Connelly Court Apts.",0],
      ["CITY02","Lightner's Luxury Suites",0],
      ["CITY03","Office Building",0],
      ["CITY04","Westwood Stock Exchange",0],
      ["CITY05","Daily Sun Times",0],
      ["CITY06","YEO-CA Cola Corp.",0],
      ["CAHOSP","Civilian Hospital",0],
      ["INGALITE","Invisible Light Post",0],
      ["INYELWLAMP","Invisible Yellow Light Post",0],
      ["INPURPLAMP","Invisible Purple Light Post",0],
      ["NEGLAMP","Negative Light Post",0],
      ["NEGRED","Negative Red Light",0],
      ["TESLA","Tesla Coil",1500,{"cat":"combat","tech":5,"side":"Soviet"}],
      ["NAMISL","Nuclear Missile Silo",5000,{"limit":1,"cat":"combat","tech":10,"side":"Soviet"}],
      ["ATESLA","Prism Cannon",1500,{"cat":"combat","tech":6,"side":"Allied"}],
      ["CAARMR","Civilian Armory",0],
      ["TSTLAMP","AlphaLightPost",0],
      ["NAHPAD","",0],
      ["AMMOCRAT","Ammo Crates",0],
      ["GAGREEN","Green Building",100,{"side":"Allied"}],
      ["NAYARD","Soviet Shipyard",1000,{"factory":"UnitType","tech":2,"side":"Soviet"}],
      ["GASPYSAT","SpySat Uplink",1500,{"cat":"combat","tech":9,"side":"Allied"}],
      ["GAGAP","Gap Generator",1000,{"cat":"combat","tech":7,"side":"Allied"}],
      ["GTGCAN","Grand Cannon",2000,{"cat":"combat","tech":7,"only":["French"],"side":"Allied"}],
      ["NANRCT","Nuclear Reactor",1000,{"tech":9,"side":"Soviet"}],
      ["GAPILL","Pill Box",500,{"cat":"combat","tech":1,"side":"Allied"}],
      ["NAFLAK","Flak Cannon",1000,{"cat":"combat","tech":4,"side":"Soviet"}],
      ["CAOUTP","Tech Outpost",0],
      ["CATHOSP","Tech Hospital",0],
      ["CAAIRP","Tech Airport",0],
      ["CAOILD","Tech Oil Derrick",0],
      ["NACLON","Cloning Vats",2500,{"limit":1,"tech":9,"side":"Soviet"}],
      ["GAOREP","Allied Ore Processor",2500,{"limit":1,"tech":10,"side":"Allied"}],
      ["CACITY01","RA2 Building",0],
      ["CACITY02","RA2 Building",0],
      ["CACITY03","RA2 Building",0],
      ["CACITY04","RA2 Building",0],
      ["CANEWY01","RA2 Building",0],
      ["CANEWY04","RA2 Statue of Liberty",0],
      ["CANEWY05","RA2 World Trade Center",0],
      ["CASWST01","RA2 Southwest Building",0],
      ["CATECH01","RA2 Communications",0],
      ["CATEXS01","RA2 Texs01 Building",0],
      ["CATEXS02","RA2 Alamo",0],
      ["CAWASH01","RA2 White House",0],
      ["CAFARM01","RA2 Farm",0],
      ["CAFARM02","RA2 Farm Silo",0],
      ["CALIT01E","RA2 Light",0],
      ["CALIT01N","RA2 Light",0],
      ["CALIT01S","RA2 Light",0],
      ["CALIT01W","RA2 Light",0],
      ["CAMISC01","RA2 Barrels",0],
      ["CAMISC02","RA2 Barrel",0],
      ["CAMISC03","RA2 Harvard's Office",0],
      ["CAMISC04","RA2 Mail Box",0],
      ["CAPOL01E","RA2 Telephone Pole",0],
      ["CAPOL01N","RA2 Telephone Pole",0],
      ["CAPOL01S","RA2 Telephone Pole",0],
      ["CAPOL01W","RA2 Telephone Pole",0],
      ["CASIN01E","RA2 Stop!",0],
      ["CASIN01N","RA2 Stop!",0],
      ["CASIN01S","RA2 Stop!",0],
      ["CASIN01W","RA2 Stop!",0],
      ["CAPARS01","RA2 Paris Tower",0],
      ["GAAIRC","Airforce Command Headquarters",1000,{"factory":"AircraftType","docks":4,"tech":3,"side":"Allied"}],
      ["CAFRMA","RA2 Farmhouse",0],
      ["CAFRMB","RA2 Outhouse",0],
      ["CAWASH05","RA2 Wash Building 5",0],
      ["CAWASH04","RA2 Wash Building 4",0],
      ["CAWASH03","RA2 Wash Building 3",0],
      ["CAWASH07","RA2 Wash Building 7",0],
      ["CAWASH11","RA2 Wash Building 11",0],
      ["CAWSH12","RA2 Washington Monument",0],
      ["CAWASH14","Jefferson Memorial",0],
      ["CAWASH09","RA2 Wash Building 9",0],
      ["CAWASH10","RA2 Wash Building 10",0],
      ["CAWASH13","RA2 Wash Building 13",0],
      ["CAARMY01","RA2 Wash Army Tent",0],
      ["CAUSFGL","RA2 US Flag Left",0],
      ["CAWASH08","RA2 Wash Building 8",0],
      ["CALIT03E","RA2 Light3E",0],
      ["CALIT03N","RA2 Light3N",0],
      ["CALIT03S","RA2 Light3S",0],
      ["CALIT03W","RA2 Light3W",0],
      ["CALIT02L","RA2 Light2L",0],
      ["CALIT02R","RA2 Light2R",0],
      ["CAHSE01","RA2 American House 01",0],
      ["CAWT01","RA2 Water Tower",0],
      ["CATS01","RA2 Twin Silos",0],
      ["CABARN02","RA2 Barn 02",0],
      ["CAWA2A","RA2 Wash Pent A",0],
      ["CAWA2B","RA2 Wash Pent B",0],
      ["CAWA2C","RA2 Wash Pent C",0],
      ["CAWA2D","RA2 Wash Pent D",0],
      ["AMRADR","American Airforce Command Headquarters",1000,{"factory":"AircraftType","docks":4,"tech":3,"only":["Americans"],"side":"Allied"}],
      ["CAPRS03","RA2 Paris Louvre",0],
      ["CAGARD01","RA2 Guard Shack",0],
      ["CARUS01","RA2 Russian Basil's Cathedral",0],
      ["CAMIAM01","RA2 Miami Hotel 01",0],
      ["CAEURO01","",0],
      ["CAMIAM02","RA2 Miami Hotel 02",0],
      ["CANWY05","RA2 NY Building 05",0],
      ["MAYAN","Mayan Prism Pyramid",0],
      ["CAEUR1","RA2 Euro Cottage A",0],
      ["CAEUR2","RA2 Euro Cottage B",0],
      ["CAEUR04","RA2 Euro Building 04",0],
      ["CAMEX01","RA2 Mayan Prism Pyramid",0],
      ["CARUS02A","RA2 Russain Kremlin Wall LTower",0],
      ["CARUS02B","RA2 Russain Kremlin Wall STower",0],
      ["CARUS02C","RA2 Russain Kremlin Wall North",0],
      ["CARUS02D","RA2 Russain Kremlin Wall East",0],
      ["CARUS02E","RA2 Russain Kremlin Wall South",0],
      ["CARUS02F","RA2 Russain Kremlin Wall West",0],
      ["CANEWY06","RA2 Wall Street Office",0],
      ["CANEWY07","RA2 Wall Street Office Var 2",0],
      ["CANEWY08","RA2 Wall Street Office Var 3",0],
      ["CAPARS02","RA2 Large Paris Building Var 1",0],
      ["CAPARS08","RA2 Large Paris Building Var 2",0],
      ["CAPARS09","RA2 Large Paris Building Var 3",0],
      ["CARUS03","RA2 Russain Kremlin Palace",0],
      ["CANEWY10","RA2 NY Building 10",0],
      ["CANEWY11","RA2 NY Building 11",0],
      ["CANEWY12","RA2 NY Building 12",0],
      ["CANEWY13","RA2 NY Building 13",0],
      ["CANEWY14","RA2 NY Building 14",0],
      ["CANEWY15","RA2 NY Building 15",0],
      ["CANEWY16","RA2 NY Building 16",0],
      ["CANEWY17","RA2 NY Building 17",0],
      ["CANEWY18","RA2 NY Building 18",0],
      ["CAPARS04","RA2 Paris Building 4",0],
      ["CAPARS05","RA2 Paris Building 5",0],
      ["CAPARS06","RA2 Paris Building 6",0],
      ["CAPARS07","RA2 Euro Phone Booth",0],
      ["CAWASH15","RA2 Lincoln Memorial",0],
      ["CAPARS10","RA2 Paris Bistro Var 1",0],
      ["CAPARS13","RA2 Paris Bistro Var 2",0],
      ["CAPARS14","RA2 Paris Bistro Var 3",0],
      ["CAGAS01","RA2 Generic Gas Station",0],
      ["CAPARS11","RA2 Paris Arc de Triumphe",0],
      ["CAPARS12","RA2 Paris Notre Dame",0],
      ["CAFARM06","RA2 Lighthouse",0],
      ["CAMIAM04","RA2 Lifeguard Hut",0],
      ["NAPSYB","RA2 Psychic Beacon",1000,{"side":"Soviet"}],
      ["NAPSYA","RA2 Psychic Amplifier",0],
      ["CAIND01","RA2 Generic Industrial building",0],
      ["CACOLO01","RA2 Air Force Academy Chapel Colorado",0],
      ["CANWY09","RA2 NY Building 09",0],
      ["CANWY22","RA2 NY Building 22",0],
      ["CANWY23","RA2 NY Building 23",0],
      ["CANWY24","RA2 NY Building 24",0],
      ["CANWY25","RA2 NY Building 25",0],
      ["CANWY26","RA2 NY Building 26",0],
      ["CATEXS03","RA2 San Antonio Office building",0],
      ["CATEXS04","RA2 San Antonio Office building Var 2",0],
      ["CATEXS05","RA2 San Antonio Office building Var 3",0],
      ["CARUS02G","RA2 Russain Kremlin Wall Clock Tower",0],
      ["CACHIG04","RA2 Chicago Associates Center",0],
      ["CAMIAM03","RA2 Miami Hotel 03",0],
      ["CARUS07","RA2 Russain Red Square Circle Thing",0],
      ["CATEXS06","RA2 Texas Office Building",0],
      ["CATEXS07","RA2 Texas Office Building var2",0],
      ["CATEXS08","RA2 Texas Office Building var3",0],
      ["CACHIG01","RA2 Chigo Brick Building",0],
      ["CACHIG02","RA2 Chigo Brick Building var2",0],
      ["CACHIG03","RA2 Chigo Office Building",0],
      ["CAWASH16","RA2 Smithsonian Castle",0],
      ["CAWASH17","RA2 Smithsonian Natural History Museum",0],
      ["CACHIG05","RA2 Chicago Sears Tower",0],
      ["CAWASH19","RA2 Iwo Jima Memorial",0],
      ["CARUS08","RA2 Russain Gum Corner",0],
      ["CARUS09","RA2 Russian Gum Middle",0],
      ["CARUS10","RA2 Russian Gum Wall N_S",0],
      ["CARUS11","RA2 Russian Gum Wall E_W",0],
      ["CANEWY20","RA2 Warehouse",0],
      ["CANEWY21","RA2 Warehouse B",0],
      ["CARUS04","RA2 Moscow City A",0],
      ["CARUS05","RA2 Moscow City B",0],
      ["CARUS06","RA2 Moscow City C",0],
      ["CAMSC01","RA2 Hot Dog Stand",0],
      ["CAMSC02","RA2 Beach Umbrellas A",0],
      ["CAMSC03","RA2 Beach Umbrellas B",0],
      ["CAMSC04","RA2 Beach Towels A",0],
      ["CAMSC05","RA2 Beach Towels B",0],
      ["CAMSC06","RA2 Camp Fire",0],
      ["CAMSC07","RA2 Thatched Hut Chief",0],
      ["CAWASH18","RA2 White House Fountain",0],
      ["CAEURO05","RA2 European Statue",0],
      ["CAPARK01","RA2 Park Bench",0],
      ["CAPARK02","RA2 Swing Set",0],
      ["CAPARK03","RA2 Merry Go Round",0],
      ["CAHSE02","RA2 American House 02",0],
      ["CAHSE03","RA2 American House 03",0],
      ["CAHSE04","RA2 American House 04",0],
      ["CASTRT01","RA2 Traffic Light",0],
      ["CASTRT02","RA2 Traffic Light",0],
      ["CASTL01","RA2 St Louis Building A",0],
      ["CASTL02","RA2 St Louis Building B",0],
      ["CASTL03","RA2 St Louis Building C",0],
      ["CASTL04","RA2 St Louis Building 04 -Arch",0],
      ["CAHSE05","RA2 American Mobile Home A",0],
      ["CAHSE06","RA2 American Mobile Home B",0],
      ["CAMIAM05","RA2 Miami Hotel 05",0],
      ["CAMIAM06","RA2 Miami Hotel 06",0],
      ["CAMIAM07","RA2 Miami Hotel 07",0],
      ["CAFNCB","Fence Black",25,{"cat":"combat"}],
      ["CAFNCW","Fence White",25,{"cat":"combat"}],
      ["CAMEX02","RA2 Mayan Castillo",0],
      ["CAMEX03","RA2 Mayan Minor Temple",0],
      ["CAMEX04","RA2 Mayan Large Temple",0],
      ["CAMEX05","RA2 Mayan Platfrom",0],
      ["CACHIG06","RA2 Chicago Water Tower",0],
      ["CAMSC08","RA2 Thatched Hut A",0],
      ["CAMSC09","RA2 Thatched Hut B",0],
      ["CAARMY02","RA2 Wash Army Tent",0],
      ["CAARMY03","RA2 Wash Army Tent",0],
      ["CAARMY04","RA2 Wash Army Tent",0],
      ["TEMMORLAMP","InvisibleTemperateMorningLamp",0],
      ["TEMDAYLAMP","InvisibleTemperateDayLamp",0],
      ["TEMDUSLAMP","InvisibleTemperateDuskLamp",0],
      ["TEMNITLAMP","InvisibleTemperateNightLamp",0],
      ["SNOMORLAMP","InvisibleSnowMorningLamp",0],
      ["SNODAYLAMP","InvisibleSnowDayLamp",0],
      ["SNODUSLAMP","InvisibleSnowDuskLamp",0],
      ["SNONITLAMP","InvisibleSnowNightLamp",0],
      ["CAKRMW","RA2 Kremlen Walls",25,{"cat":"combat"}],
      ["CARUFGL","RA2 RU Flag Left",0],
      ["CAFRFGL","RA2 FR Flag Left",0],
      ["CAIRSFGL","",0],
      ["CACUFGL","RA2 CU Flag Left",0],
      ["CASKFGL","RA2 SK Flag Left",0],
      ["CALBFGL","RA2 LB Flag Left",0],
      ["CAMIAM08","RA2 Arizona Memorial",0],
      ["CAMISC05","RA2 Stack O Pipes",0],
      ["CAMISC06","RA2 V3 Rack",0],
      ["CASTL05A","RA2 Busch Stadium A",0],
      ["CASTL05B","RA2 Busch Stadium B",0],
      ["CASTL05C","RA2 Busch Stadium C",0],
      ["CASTL05D","RA2 Busch Stadium D",0],
      ["CASTL05E","RA2 Busch Stadium E",0],
      ["CASTL05F","RA2 Busch Stadium F",0],
      ["CASTL05G","RA2 Busch Stadium G",0],
      ["CASTL05H","RA2 Busch Stadium H",0],
      ["CAMSC10","RA2 McBurger Kong",0],
      ["CAGEFGL","RA2 GE Flag Left",0],
      ["CAUKFGL","RA2 UK Flag Left",0],
      ["CAWASH06","RA2 Wash Building 6",0],
      ["CAMSC11","RA2 Tires",0],
      ["CAMSC12","RA2 Bullseye",0],
      ["CAMSC13","RA2 Derelict Tank",0],
      ["CAPOFGL","RA2 PO Flag Left",0],
      ["CAMSC12A","RA2 Bullseye 2",600],
      ["CAMOV01","RA2 Drive In Movie Screen",0],
      ["CAMOV02","RA2 Drive In Movie Concession Stand",0],
      ["CABUNK01","RA2 Concrete Bunker 01",0],
      ["CABUNK02","RA2 Concrete Bunker 02",0],
      ["CAFNCP","Fence Prison Camp",25,{"cat":"combat"}],
      ["CASTRT03","RA2 Traffic Light",0],
      ["CASTRT04","RA2 Traffic Light",0],
      ["CASTRT05","RA2 Bus Stop",0],
    ],
    infantry: [
      ["E1","GI",200,{"tech":1,"side":"Allied"}],
      ["E2","Conscript",100,{"tech":1,"side":"Soviet"}],
      ["SHK","Shock Trooper",500,{"tech":5,"side":"Soviet"}],
      ["ENGINEER","Engineer",500,{"tech":1}],
      ["JUMPJET","Rocketeer",600,{"tech":3,"side":"Allied"}],
      ["GHOST","SEAL",1000,{"side":"Allied"}],
      ["YURI","Yuri",1200,{"tech":10,"side":"Soviet"}],
      ["IVAN","Crazy Ivan",600,{"tech":5,"side":"Soviet"}],
      ["DESO","Desolater",600,{"tech":8,"only":["Arabs"],"side":"Soviet"}],
      ["DOG","Attack Dog",200,{"tech":2}],
      ["CIV1","Civilian",10],
      ["CIV2","Civilian",10],
      ["CIV3","Civilian",10],
      ["CTECH","Technician",10],
      ["WEEDGUY","Chem Spray Infantry",300],
      ["CLEG","Chrono Legionnaire",1500,{"tech":10,"side":"Allied"}],
      ["SPY","Spy",1000,{"tech":5,"side":"Allied"}],
      ["CCOMAND","Chrono Commando",2000,{"tech":9,"side":"Allied"}],
      ["PTROOP","Psi-Corp Trooper",1000,{"tech":9,"side":"Allied"}],
      ["CIVAN","Chrono Ivan",1000,{"tech":9,"side":"Soviet"}],
      ["YURIPR","Yuri Prime",2000,{"limit":1,"tech":9,"side":"Soviet"}],
      ["SNIPE","Sniper",600,{"tech":1,"only":["British"],"side":"Allied"}],
      ["COW","Cow",10],
      ["ALL","Herbert the Alligator",10],
      ["TANY","Tanya",1000,{"tech":9,"side":"Allied"}],
      ["FLAKT","Flak Trooper",300,{"tech":1,"side":"Soviet"}],
      ["TERROR","Terrorist",200,{"tech":5,"only":["Confederation"],"side":"Soviet"}],
      ["SENGINEER","Soviet Engineer",500,{"tech":1}],
      ["ADOG","Allied Attack Dog",200,{"tech":2}],
      ["VLADIMIR","Vladimir",10],
      ["PENTGEN","General Pentagon",10],
      ["PRES","President",10],
      ["SSRV","Secret Service",10],
      ["CIVA","Civilian Texan A",10],
      ["CIVB","Civilian Texan B",10],
      ["CIVC","Civilian Texan C",10],
      ["CIVBBP","Civilian Baseball Player",10],
      ["CIVBFM","Civilian Beach Fat Male",10],
      ["CIVBF","Civilian Beach Female",10],
      ["CIVBTM","Civilian Beach Thin Male",10],
      ["CIVSFM","Civilian Snow Fat Male",10],
      ["CIVSF","Civilian Snow Female",10],
      ["CIVSTM","Civilian Snow Thin Male",10],
      ["POLARB","Frosty the Polar Bear",10],
      ["JOSH","Josh the Monkey",10],
    ],
    vehicle: [
      ["AMCV","Allied Construction Vehicle",3000,{"tech":10,"side":"Allied"}],
      ["HARV","War Miner",1400,{"tech":1,"side":"Soviet"}],
      ["APOC","Apocalypse",1750,{"tech":7,"side":"Soviet"}],
      ["HTNK","Rhino Heavy Tank",900,{"tech":2,"side":"Soviet"}],
      ["SAPC","Armored Transport",900,{"tech":2,"side":"Soviet"}],
      ["CAR","Automobile",0,{"side":"Soviet"}],
      ["BUS","School Bus",0,{"side":"Soviet"}],
      ["WINI","Recreational Vehicle",0,{"side":"Soviet"}],
      ["PICK","Pickup Truck",0,{"side":"Soviet"}],
      ["MTNK","Grizzly Battle Tank",700,{"tech":2,"side":"Allied"}],
      ["HORV","War Miner",1400],
      ["TRUCKA","Truck",500],
      ["TRUCKB","Truck (loaded)",500],
      ["CARRIER","Aircraft Carrier",2000,{"tech":7,"side":"Allied"}],
      ["V3","V3 Launcher",800,{"tech":3,"side":"Soviet"}],
      ["ZEP","Kirov Airship",2000,{"tech":10,"side":"Soviet"}],
      ["DRON","Terror Drone",500,{"tech":4,"side":"Soviet"}],
      ["HTK","Flak Track",500,{"tech":3,"side":"Soviet"}],
      ["DEST","Destroyer",1000,{"tech":4,"side":"Allied"}],
      ["SUB","Typhoon Attack Sub",1000,{"tech":2,"side":"Soviet"}],
      ["AEGIS","Aegis Cruiser",1200,{"tech":7,"side":"Allied"}],
      ["LCRF","Landing Craft",900,{"tech":4,"side":"Allied"}],
      ["DRED","Dreadnought",2000,{"tech":6,"side":"Soviet"}],
      ["SHAD","BlackHawk Transport",1000,{"tech":7,"side":"Allied"}],
      ["SQD","Giant Squid",1000,{"tech":9,"side":"Soviet"}],
      ["DLPH","Dolphin",500,{"tech":5,"side":"Allied"}],
      ["SMCV","Soviet Construction Vehicle",3000,{"tech":10,"side":"Soviet"}],
      ["TNKD","Tank Destroyer",900,{"tech":2,"only":["Germans"],"side":"Allied"}],
      ["HOWI","Howitzer",750,{"only":["Alliance"],"side":"Allied"}],
      ["TTNK","Tesla Tank",1200,{"tech":10,"only":["Russians"],"side":"Soviet"}],
      ["HIND","Hind Transport",1000,{"only":["Confederation"],"side":"Soviet"}],
      ["LTNK","Light Tank",600,{"only":["Arabs"],"side":"Soviet"}],
      ["CMON","Chrono Miner(noback)",1400],
      ["CMIN","Chrono Miner",1400,{"tech":1,"side":"Allied"}],
      ["SREF","Prism Tank",1200,{"tech":8,"side":"Allied"}],
      ["XCOMET","Placeholder",2000,{"side":"Allied"}],
      ["HYD","Sea Scorpion",600,{"tech":6,"side":"Soviet"}],
      ["MGTK","Mirage Tank",1000,{"tech":9,"side":"Allied"}],
      ["FV","IFV",600,{"tech":3,"side":"Allied"}],
      ["DeathDummy","",0],
      ["VLAD","Vladimir's Dreadnought",2500,{"side":"Soviet"}],
      ["DTRUCK","Demolitions Truck",1500,{"tech":10,"only":["Africans"],"side":"Soviet"}],
      ["PROPA","RA2 Propaganda Truck",0,{"side":"Soviet"}],
      ["CONA","RA2 Construction Excavator",0,{"side":"Soviet"}],
      ["COP","RA2 Pig",0,{"side":"Soviet"}],
      ["EUROC","RA2 European Car A",0,{"side":"Soviet"}],
      ["LIMO","RA2 Limo",0,{"side":"Soviet"}],
      ["STANG","RA2 Sports Car",0,{"side":"Soviet"}],
      ["SUVB","RA2 SUV Black",0,{"side":"Soviet"}],
      ["SUVW","RA2 SUV White",0,{"side":"Soviet"}],
      ["TAXI","RA2 Taxi",0,{"side":"Soviet"}],
      ["PTRUCK","RA2 Pickup Truck",0,{"side":"Soviet"}],
      ["CRUISE","RA2 Cruise Ship",500,{"side":"Soviet"}],
      ["TUG","RA2 Tug Boat",500,{"side":"Soviet"}],
      ["CDEST","Coast Guard Boat",1000],
    ],
    aircraft: [
      ["APACHE","",0],
      ["ORCA","Intruder",1200,{"tech":3}],
      ["HORNET","Hornet",50],
      ["V3ROCKET","V3 Rocket",50],
      ["ASW","Osprey",50],
      ["DMISL","Dread Missile",50],
      ["PDPLANE","Cargo Plane",0],
      ["BEAG","Black Eagle",1200,{"tech":3,"only":["Alliance"]}],
      ["CARGOPLANE","Transport Plane",0],
    ],
  };
  window.__cdcReplayRules = {"maximumQueuedObjects":29,"buildSpeed":0.7,"multipleFactory":0.8,"padAircraft":["ORCA","BEAG"]};
})();
